### PR TITLE
[Suggestion] Text streaming for OpenAI

### PR DESCRIPTION
**Pull request by barisozmen**
This PR implements real-time text streaming capability for the OpenAI provider, allowing users to see LLM responses as they are generated - similar to the ChatGPT interface.

#### Validation
- I self-validated it through the example in `examples/generate_stream_text.py`. The newly created `generate_stream_text()` prints to the console via streaming, chunk by chunk.

#### Future
- If this PR accepted, I'd like to implement it for other providers.

#33 

## Summary by CodeRabbit

- **New Features**
	- Introduced real-time text generation and streaming functionality.
	- Added a `generate_stream_text` method to facilitate immediate output from specified language models.
	- Enhanced the OpenAI integration to support streaming responses.

- **Bug Fixes**
	- No bug fixes were included in this release.

- **Documentation**
	- Updated documentation to reflect the new streaming text generation capabilities.

### CODE REVIEW

**Comment by kennethreitz** [comment]
why don't we change it to `generate_text(..., stream=True)`? Thoughts?

**Comment by kennethreitz** [comment]
Merged this into `streaming` branch in the meantime. Will play with it.

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by barisozmen** [comment]
> why don't we change it to `generate_text(..., stream=True)`? Thoughts?

I think that can work as well. I'm indifferent between two choices. In case they're to be merged, the return type should become Generator | str, instead of str and Generator separately. Also, the response return logic should be conditioned by if/else. Another consideration is when adding logging and caching mechanisms. For the streaming, they should collect all the chunks, and then combine them when the streaming ends. 

I'm not sure which decision would make it easier to handle caching/logging situations.

**Comment by kennethreitz** [comment]
already merged and released :)

**Comment by barisozmen** [comment]
Ah, okay :)

**Pull request merged**
