### PR TITLE
feat: add function calling (tools)

### PR DESCRIPTION
**Pull request by lucianosrp**
Closes : #40  (partially)

### Remarks:
I mainly worked on Anthropic as it is the provider I am the most familiar with!
OpenAI is passing all tests except for the `tool` decorator

I won't have time to implement the other providers so we could: 
1- Merge it with a "Supported providers" list on the README + `NotImplementedError` for all other providers
2- Keep this PR _WIP_  until the other providers have been implemented

-----

This PR is a first implementation for Function Calling (tools). 

It introduces a new model ( `BaseTool` ) which provides the main interface to convert python function to _Tools_
Tools implementations can be quickly accessed via the `BaseProvider.tool`  property. 

Each tool needs to implement 3 methods:

```python
    @abstractmethod
    def get_input_schema(self) -> Any: ... 

    @abstractmethod
    def handle(self, message) -> None: ...

    @abstractmethod
    def get_response_schema(self) -> Any: ...
  ```
  
  `handle` is responsible to do the heavy work of : 
- Iterating over the API's messages
- Executing the python function

the `send_conversation` method has been slightly tweaked to iterate over each defined tool to check if they have been called. This requires a while loop since the LLM may or may not use sequential tool calls or multiple tool calls in one response.

> Please see [examples/distance_calculator.py](examples/distance_calculator.py) for a practical example! 

### Hiding in-between LLM's messages
This current implementation _hides_ intermediate  messages while calling one or multiple tools (so far, I think Claude is the only one who does it)
image
We could expose them eventually at some point, but I think the user should only be concerned with the final tool's result.

 
### What's next:
- [ ] add other providers
- [ ] improve testing
- [ ] fetch bugs
- [ ] simplify where possible
    
 ---- 
 Overall, I am 100% flexible on how this implementation should look like and I am open to discuss any changes :) I had lots of fun working on this! 
 
 Ps: I will be taking a break next week!

### CODE REVIEW

**Comment by kennethreitz** [comment]
so excited about this

**Comment by lucianosrp** [comment]
Still cooking 🍳

**Comment by kennethreitz** [comment]
love the attention to detail

**Comment by kennethreitz** [comment]
so good! ✨🍰✨

**Pull request merged**
